root = "."
testdata_dir = "testdata"

[build]
cmd = "./scripts/run-go-tests.sh -v"
args = []                # Replace default args with test command
# Binary name after build (not used in this setup)
bin = ""
# Specify working directory if needed
full_bin = ""
# Timeout for the build process
delay = 2000           # in milliseconds
kill_signal = "SIGINT"
# Patterns to watch
exclude_dir = [
  "tmp",
  "vendor",
  "testdata",
  "postgres-data",
  "static",
  "py-embed",
  "e2e",
]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "templ", "json"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[run]
cmd = ""

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
